### PR TITLE
feat(api): support oidc username claim

### PR DESCRIPTION
**Pull request by sbor23**

### CODE REVIEW

**Review by czosel — APPROVED** [review]

**Comment by sbor23** [comment]
@czosel FYI: I'm not authorized to merge this.

**Comment by czosel** [comment]
cc @anehx

**Comment by anehx** [comment]
What is this and are you aware that this will break the production envs (since we map the username to `sub`)?

**Comment by hairmare** [comment]
> @czosel FYI: I'm not authorized to merge this.

I updated the default orga perms to allow all members to write to all repos in the orga.

You should probably still look into @anehx's feedback before merging though.

**Comment by czosel** [comment]
@hairmare thanks!

@anehx We want to move away from using `sub` in order to be able to switch to the other keycloak instance. Let's not merge before today's prod deploy though.

**Comment by anehx** [comment]
Then you should update the caluma setting as well..

**Comment by sbor23** [comment]
> Then you should update the caluma setting as well..

True, I added the caluma variable.

**Comment by sbor23** [comment]
> @anehx We want to move away from using `sub` in order to be able to switch to the other keycloak instance. Let's not merge before today's prod deploy though.

Yes definitely holding out on this one!

**Pull request merged**
