### PR TITLE
feat(dms): add application name to EXTENSIONS_ARGUMENTS

### PR DESCRIPTION
**Pull request by maria-pw**

### CODE REVIEW

**Review by derrabauke — APPROVED** [review]
LGTM :+1:

**Comment by derrabauke** [comment]
@luytena second review appreciated

**Comment by luytena** [comment]
Is camac_application an existing variable or does it have to be newly set?

**Comment by maria-pw** [comment]
> Is camac_application an existing variable or does it have to be newly set?

It is an existing variable from what I can tell, see other usage here: https://github.com/camac-suisse/ansible-role-camac/blob/853fecee887ad605d20eb726f0d520b037113ae5/templates/camac_api_env.j2#L23

**Comment by luytena** [comment]
> > Is camac_application an existing variable or does it have to be newly set?
> 
> It is an existing variable from what I can tell, see other usage here:
> 
> https://github.com/camac-suisse/ansible-role-camac/blob/853fecee887ad605d20eb726f0d520b037113ae5/templates/camac_api_env.j2#L23

Perfect, thanks!

**Review by luytena — APPROVED** [review]
LGTM :+1:

**Pull request merged**
